
import { Plan, User, UserRole, AdminConfig } from '../types';

// --- Constants ---
const MOCK_DELAY = 600;

// --- Plan Limits (Monthly) ---
export const PLAN_LIMITS = {
  [Plan.FREE]: { words: 3000, undetectable: 500, pdfs: 3 },
  [Plan.BASIC]: { words: 25000, undetectable: 5000, pdfs: 15 },
  [Plan.PRO]: { words: 100000, undetectable: 10000, pdfs: 50 },
  [Plan.ULTRA]: { words: 999999999, undetectable: 50000, pdfs: 200 } // Unlimited represented as high number
};

// --- Mock Database State ---
let currentUser: User | null = null;
let adminSettings: AdminConfig = {
  stripeKey: 'sk_test_123456789',
  geminiKey: 'AIzaSy-default-mock-key',
  adminUser: 'admin',
  adminPass: 'admin'
};

const defaultUser: User = {
  id: 'user-1',
  email: 'user@example.com',
  name: 'John Doe',
  plan: Plan.FREE,
  role: UserRole.USER,
  wordsUsed: 1200,
  undetectableWordsUsed: 0,
  avatar: 'https://picsum.photos/201'
};

const mockUsers: User[] = [
  defaultUser,
  { id: 'u2', email: 'sarah@edu.com', name: 'Sarah Smith', plan: Plan.PRO, role: UserRole.USER, wordsUsed: 45000, undetectableWordsUsed: 2000, avatar: 'https://picsum.photos/202' },
  { id: 'u3', email: 'mike@test.com', name: 'Mike Jones', plan: Plan.BASIC, role: UserRole.USER, wordsUsed: 12000, undetectableWordsUsed: 4500, avatar: 'https://picsum.photos/203' },
  { id: 'u4', email: 'ahmed@uae.ae', name: 'Ahmed Ali', plan: Plan.ULTRA, role: UserRole.USER, wordsUsed: 150000, undetectableWordsUsed: 1000, avatar: 'https://picsum.photos/204' },
];

const mockPayments = [
  { id: 'pay_1', user: 'sarah@edu.com', amount: 27.99, date: '2023-10-25', status: 'Succeeded' },
  { id: 'pay_2', user: 'mike@test.com', amount: 13.99, date: '2023-10-24', status: 'Succeeded' },
  { id: 'pay_3', user: 'ahmed@uae.ae', amount: 69.99, date: '2023-10-23', status: 'Succeeded' },
];

// --- Service Methods ---

export const AuthService = {
  login: async (email: string, password: string): Promise<User> => {
    await new Promise(resolve => setTimeout(resolve, MOCK_DELAY));
    
    // Dynamic Admin Check
    if (email === adminSettings.adminUser && password === adminSettings.adminPass) {
      currentUser = {
        id: 'admin-1',
        email: adminSettings.adminUser + '@system.com',
        name: 'System Administrator',
        plan: Plan.PRO,
        role: UserRole.ADMIN,
        wordsUsed: 0,
        undetectableWordsUsed: 0,
        avatar: 'https://picsum.photos/200'
      };
      return currentUser;
    }
    
    // Default User Login
    currentUser = { ...defaultUser, email, name: email.split('@')[0] };
    return currentUser;
  },

  socialLogin: async (provider: 'google' | 'apple'): Promise<User> => {
    await new Promise(resolve => setTimeout(resolve, MOCK_DELAY));
    currentUser = { ...defaultUser, name: `${provider === 'google' ? 'Google' : 'Apple'} User` };
    return currentUser;
  },

  logout: async () => {
    currentUser = null;
  },

  getCurrentUser: () => currentUser,
  
  updateUserPlan: (newPlan: Plan) => {
    if (currentUser) {
      currentUser.plan = newPlan;
    }
  },

  updateUsage: (words: number, undetectable: boolean) => {
    if (currentUser) {
      currentUser.wordsUsed += words;
      if (undetectable) {
        currentUser.undetectableWordsUsed += words;
      }
    }
  }
};

export const AIService = {
  streamResponse: async (
    prompt: string, 
    onChunk: (text: string) => void,
    onComplete: () => void
  ) => {
    // Basic auth check
    if (!currentUser) throw new Error("Unauthorized");
    
    // Check Limits
    const limits = PLAN_LIMITS[currentUser.plan];
    if (currentUser.wordsUsed >= limits.words) {
      throw new Error("Word quota exceeded");
    }

    await new Promise(r => setTimeout(r, 500));

    // In a real implementation, we would use adminSettings.geminiKey to initialize GoogleGenAI here.
    // const genAI = new GoogleGenAI(adminSettings.geminiKey);
    
    const mockResponses = [
      "Here is the content generated by the ThesisGPT AI (Powered by Google Gemini). ",
      "It has analyzed your request specifically for academic context. ",
      "The methodology described aligns with standard research practices. ",
      "Furthermore, the model ensures high coherence and vocabulary richness. ",
      "This concludes the simulated generated response."
    ];

    let fullText = "";
    for (const chunk of mockResponses) {
      await new Promise(r => setTimeout(r, 100));
      fullText += chunk;
      onChunk(fullText);
    }

    // Estimate words (mock calculation)
    const wordCount = fullText.split(' ').length;
    const isUndetectable = prompt.includes("Undetectable: true");
    AuthService.updateUsage(wordCount, isUndetectable);
    
    onComplete();
  }
};

export const AdminService = {
  getStats: () => ({
    totalRevenue: 12450.00,
    activeUsers: 1240,
    tokensBurned: 45000000,
    serverCost: 112.50
  }),
  
  getSettings: () => ({ ...adminSettings }),
  
  updateSettings: async (newSettings: AdminConfig) => {
    await new Promise(r => setTimeout(r, 500));
    adminSettings = newSettings;
    return adminSettings;
  },

  getUsers: () => mockUsers,
  
  getPayments: () => mockPayments
};
