
import { Plan, User, UserRole, AdminConfig } from '../types';

// --- Constants ---
const MOCK_DELAY = 600;

// --- Mock Database State ---
let currentUser: User | null = null;
let adminSettings: AdminConfig = {
  stripeKey: 'sk_test_123456789',
  kimiKey: 'sk-kimi-default-key',
  adminUser: 'admin',
  adminPass: 'admin'
};

const defaultUser: User = {
  id: 'user-1',
  email: 'user@example.com',
  name: 'John Doe',
  plan: Plan.FREE,
  role: UserRole.USER,
  gensUsed: 5,
  avatar: 'https://picsum.photos/201'
};

const mockUsers: User[] = [
  defaultUser,
  { id: 'u2', email: 'sarah@edu.com', name: 'Sarah Smith', plan: Plan.PRO, role: UserRole.USER, gensUsed: 1450, avatar: 'https://picsum.photos/202' },
  { id: 'u3', email: 'mike@test.com', name: 'Mike Jones', plan: Plan.STARTER, role: UserRole.USER, gensUsed: 42, avatar: 'https://picsum.photos/203' },
  { id: 'u4', email: 'ahmed@uae.ae', name: 'Ahmed Ali', plan: Plan.PRO, role: UserRole.USER, gensUsed: 890, avatar: 'https://picsum.photos/204' },
];

const mockPayments = [
  { id: 'pay_1', user: 'sarah@edu.com', amount: 19.00, date: '2023-10-25', status: 'Succeeded' },
  { id: 'pay_2', user: 'mike@test.com', amount: 9.00, date: '2023-10-24', status: 'Succeeded' },
  { id: 'pay_3', user: 'ahmed@uae.ae', amount: 19.00, date: '2023-10-23', status: 'Succeeded' },
  { id: 'pay_4', user: 'john@doe.com', amount: 9.00, date: '2023-10-20', status: 'Failed' },
];

// --- Service Methods ---

export const AuthService = {
  login: async (email: string, password: string): Promise<User> => {
    await new Promise(resolve => setTimeout(resolve, MOCK_DELAY));
    
    // Dynamic Admin Check
    if (email === adminSettings.adminUser && password === adminSettings.adminPass) {
      currentUser = {
        id: 'admin-1',
        email: adminSettings.adminUser + '@system.com',
        name: 'System Administrator',
        plan: Plan.PRO,
        role: UserRole.ADMIN,
        gensUsed: 0,
        avatar: 'https://picsum.photos/200'
      };
      return currentUser;
    }
    
    // Default User Login
    currentUser = { ...defaultUser, email, name: email.split('@')[0] };
    return currentUser;
  },

  socialLogin: async (provider: 'google' | 'apple'): Promise<User> => {
    await new Promise(resolve => setTimeout(resolve, MOCK_DELAY));
    currentUser = { ...defaultUser, name: `${provider === 'google' ? 'Google' : 'Apple'} User` };
    return currentUser;
  },

  logout: async () => {
    currentUser = null;
  },

  getCurrentUser: () => currentUser,
  
  updateUserQuota: (newCount: number) => {
    if (currentUser) {
      currentUser.gensUsed = newCount;
    }
  }
};

export const KimiService = {
  streamResponse: async (
    prompt: string, 
    onChunk: (text: string) => void,
    onComplete: () => void
  ) => {
    // Basic auth check
    if (!currentUser) throw new Error("Unauthorized");
    
    await new Promise(r => setTimeout(r, 500));

    const mockResponses = [
      "Here is the content generated by the Kimi-2 Turbo engine. ",
      "It has analyzed your request specifically for academic context. ",
      "The methodology described aligns with standard research practices. ",
      "Furthermore, the Kimi-2 model ensures high coherence and vocabulary richness. ",
      "This concludes the simulated generated response."
    ];

    let fullText = "";
    for (const chunk of mockResponses) {
      await new Promise(r => setTimeout(r, 100));
      fullText += chunk;
      onChunk(fullText);
    }

    AuthService.updateUserQuota(currentUser.gensUsed + 1);
    onComplete();
  }
};

export const AdminService = {
  getStats: () => ({
    totalRevenue: 12450.00,
    activeUsers: 1240,
    tokensBurned: 45000000,
    serverCost: 112.50
  }),
  
  getSettings: () => ({ ...adminSettings }),
  
  updateSettings: async (newSettings: AdminConfig) => {
    await new Promise(r => setTimeout(r, 500));
    adminSettings = newSettings;
    return adminSettings;
  },

  getUsers: () => mockUsers,
  
  getPayments: () => mockPayments
};
